### ISSUE TITLE
메뉴타입은 어떻게 가져오나요

### ISSUE THREAD

**Issue by malibinYun** [Java-Bom/cafe#6]
![image](https://user-images.githubusercontent.com/44341119/88169199-a1add800-cc56-11ea-9268-083b07499bce.png)

요놈인거거같긴한데..

![image](https://user-images.githubusercontent.com/44341119/88169338-d02bb300-cc56-11ea-8d98-2eb27f0f1dd5.png)

이렇게게 갖고오는것 까진 코드보면 알겠는데, 이 담에 $menuTypeInput에 데이터가 뭘로 떨어지는지를 모르겠네요. 타입도 모르겠고.. 그냥 찍어보는게 답인가요?

**Comment by Gobukgol** [comment]
음 내 생각인데 String 값으로 menuType이 들어오지않을까?? 

![image](https://user-images.githubusercontent.com/34976178/88169858-a0c97600-cc57-11ea-8993-e0f7ec6b86bd.png)

우리 메뉴 관리 페이지인데 저기에서 선택한 값이 String 값으로 'CAKE' 나 'BEVERAGE' 로 들어와서 이걸 java 코드에서 Category enum 으로 바꿔서 사용하는거라고 생각하고는 있어

**Comment by malibinYun** [comment]
나도 비슷한 생각은 하긴했는데 정확하게 타입이랑 뭐떨어지는지 알고싶어서리
TestCode 처럼 바로 Enum으로 바꿔주면 좋겟지만.. 그렇지 않을수도있으니까. 직접 찍어보고싶은데 자꾸 돌리면 죽네 ^_^;;;

**Comment by pci2676** [comment]
```javascript
const type = document.getElementById("menu-type-select")
const selectedIndex = type.selectedIndex
const typeText = type.options[selectedIndex].text
const typeValue = type.options[selectedIndex].value
```
이렇게 하면 될 듯

**Comment by malibinYun** [comment]
![image](https://user-images.githubusercontent.com/44341119/88170898-66f96f00-cc59-11ea-904e-6ed908958c02.png)

이놈이군요? 찾았습니다 휴

**Comment by pci2676** [comment]
아 뿌려줄때를 말한거구나 ㅋㅋ 굳

해결 됐으니 이슈는 닫도록 하겠습니다~

**Comment by malibinYun** [comment]
아 노노 꺼내오는거 말하는게 맞긴한데 순서도 따로 가져와야되는구나 흠
일단 형이 알려준대로 하겠슴
